#baseurl = "https://oxidecomputer.com"
languageCode = "en-us"
title = "Oxide Computer Company"
canonifyUrls = true

[params]
description = "Hyperscaler infrastructure for the rest of us"
github_handle = "oxidecomputer"
twitter_handle = "oxidecomputer"
google_analytics = "UA-148178470-1"
signup_form_url = "https://oxidecomputer.us20.list-manage.com/subscribe?u=e46acf89cdf1f5bddf3136473&id=8a6d823488"
twitter_id = "1161434275197009921"
facebook_id = "1018260045"

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
  department = "departments"

[permalinks]
	categories = "/blog/categories/:slug/"
	tags = "/blog/tags/:slug/"
	authors = "/blog/authors/:slug/"
	departments = "/careers/departments/:slug/"
