baseurl = "https://oxide.computer"
languageCode = "en-us"
title = "Oxide Computer Company"
canonifyUrls = true

[params]
description = "Hyperscaler infrastructure for the rest of us"
github_handle = "oxidecomputer"
twitter_handle = "oxidecomputer"
linkedin_url = "https://www.linkedin.com/company/oxidecomputer"
google_analytics = "UA-148178470-1"
signup_form_url = "https://oxidecomputer.us20.list-manage.com/subscribe?u=e46acf89cdf1f5bddf3136473&id=8a6d823488"
twitter_id = "1161434275197009921"
facebook_id = "1018260045"
itunes_url = "https://podcasts.apple.com/us/podcast/on-the-metal/id1488187473"
android_url = "https://www.google.com/podcasts?feed=aHR0cHM6Ly9mZWVkcy50cmFuc2lzdG9yLmZtL29uLXRoZS1tZXRhbC0wMjk0NjQ5ZS1lYzIzLTRlYWItOTc1YS05ZWIxM2ZkOTRlMDY%3D"
google_play_url = "https://play.google.com/music/m/Iycdfnasjwyvpe7ona6zwjwhkr4?t=On_The_Metal"
stitcher_url = ""
pocketcasts_url = "https://pca.st/gg2yq8h0"
spotify_url = "https://open.spotify.com/show/4GDUravTUbvTrdJ2oWnzJp"
podcast_rss_feed = "https://feeds.transistor.fm/on-the-metal-0294649e-ec23-4eab-975a-9eb13fd94e06"

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
  department = "departments"

[permalinks]
	categories = "/blog/categories/:slug/"
	tags = "/blog/tags/:slug/"
	authors = "/blog/authors/:slug/"
	departments = "/careers/departments/:slug/"
